# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 st=2 et :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false

  # Limiter la RAM des VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "700"
    vb.gui = false
  end

  # Mettre en place un cache pour APT
  # config.vm.synced_folder 'v-cache', '/var/cache/apt'
# """"""""my configuration of DNSmasq"
#  config.dsmasq.enable =  true 
#  config.dnsmasq.domain = 's0.infra'
# """""""my configuration of DNSmasq"

  config.vm.define 's0.info' do |machine|
    machine.vm.hostname = 's0.info'
    machine.vm.network "private_network", ip: "192.168.50.250" 
  end

  # 192.168.50.10
  # 192.168.50.20
  # 192.168.50.30
  # 192.168.50.40
  4.times do |idx|
    config.vm.define "s#{idx}.info" do |machine|
      machine.vm.hostname = "s#{idx}.info" 
      machine.vm.network "private_network", type: "dhcp"
      if idx == 0 
        machine.vm.network "forwarded_port", guest: 80, host: 1080
        machine.vm.network "forwarded_port", guest: 8080, host: 8080
      end
    end
  end

  config.vm.provision "shell", path: "provision.sh"
end

